[2024-03-31T01:07:03.030+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: billboard_to_spotify_to_s3_extractionV1.top_10_billboard_artist scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-03-31T01:07:03.049+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: billboard_to_spotify_to_s3_extractionV1.top_10_billboard_artist scheduled__2024-03-30T00:00:00+00:00 [queued]>
[2024-03-31T01:07:03.050+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 6
[2024-03-31T01:07:03.079+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): top_10_billboard_artist> on 2024-03-30 00:00:00+00:00
[2024-03-31T01:07:03.090+0000] {standard_task_runner.py:60} INFO - Started process 9086 to run task
[2024-03-31T01:07:03.096+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'billboard_to_spotify_to_s3_extractionV1', 'top_10_billboard_artist', 'scheduled__2024-03-30T00:00:00+00:00', '--job-id', '1515', '--raw', '--subdir', 'DAGS_FOLDER/billboard_to_spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmp2x_e50j6']
[2024-03-31T01:07:03.101+0000] {standard_task_runner.py:88} INFO - Job 1515: Subtask top_10_billboard_artist
[2024-03-31T01:07:03.197+0000] {task_command.py:423} INFO - Running <TaskInstance: billboard_to_spotify_to_s3_extractionV1.top_10_billboard_artist scheduled__2024-03-30T00:00:00+00:00 [running]> on host bdb7303f046f
[2024-03-31T01:07:03.361+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='billboard_to_spotify_to_s3_extractionV1' AIRFLOW_CTX_TASK_ID='top_10_billboard_artist' AIRFLOW_CTX_EXECUTION_DATE='2024-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-30T00:00:00+00:00'
[2024-03-31T01:07:03.365+0000] {logging_mixin.py:188} INFO - getting top artist
[2024-03-31T01:07:08.659+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1073, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.billboard.com', port=443): Max retries exceeded with url: /charts/artist-100/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/billboard_to_spotify_to_csvs_to_s3.py", line 72, in get_top_artist
    html_content = page_content('https://www.billboard.com/charts/artist-100/')
  File "/opt/airflow/dags/billboard_to_spotify_to_csvs_to_s3.py", line 64, in page_content
    r = requests.get(url)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.billboard.com', port=443): Max retries exceeded with url: /charts/artist-100/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)')))
[2024-03-31T01:07:08.675+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=billboard_to_spotify_to_s3_extractionV1, task_id=top_10_billboard_artist, execution_date=20240330T000000, start_date=20240331T010703, end_date=20240331T010708
[2024-03-31T01:07:08.692+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1515 for task top_10_billboard_artist (HTTPSConnectionPool(host='www.billboard.com', port=443): Max retries exceeded with url: /charts/artist-100/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))); 9086)
[2024-03-31T01:07:08.734+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-31T01:07:08.764+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
