[2024-03-21T07:36:31.022+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-21T06:20:00+00:00 [queued]>
[2024-03-21T07:36:31.081+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-21T06:20:00+00:00 [queued]>
[2024-03-21T07:36:31.091+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-03-21T07:36:31.226+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_s3_connection> on 2024-03-21 06:20:00+00:00
[2024-03-21T07:36:31.255+0000] {standard_task_runner.py:60} INFO - Started process 2338 to run task
[2024-03-21T07:36:31.268+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3_data_extraction_v1', 'create_s3_connection', 'scheduled__2024-03-21T06:20:00+00:00', '--job-id', '451', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpp5_kmod1']
[2024-03-21T07:36:31.294+0000] {standard_task_runner.py:88} INFO - Job 451: Subtask create_s3_connection
[2024-03-21T07:36:31.512+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-21T06:20:00+00:00 [running]> on host ca1809388db1
[2024-03-21T07:36:32.133+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='spotify_to_s3_data_extraction_v1' AIRFLOW_CTX_TASK_ID='create_s3_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T06:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T06:20:00+00:00'
[2024-03-21T07:36:32.160+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_to_csvs_to_s3.py", line 143, in _create_connection
    raise AirflowFailException("Environment variables were not passed")
airflow.exceptions.AirflowFailException: Environment variables were not passed
[2024-03-21T07:36:32.241+0000] {taskinstance.py:1149} INFO - Immediate failure requested. Marking task as FAILED. dag_id=spotify_to_s3_data_extraction_v1, task_id=create_s3_connection, execution_date=20240321T062000, start_date=20240321T073631, end_date=20240321T073632
[2024-03-21T07:36:32.322+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 451 for task create_s3_connection (Environment variables were not passed; 2338)
[2024-03-21T07:36:32.442+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-21T07:36:32.717+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
