[2024-03-23T20:57:14.241+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-21T05:17:00+00:00 [queued]>
[2024-03-23T20:57:14.254+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-21T05:17:00+00:00 [queued]>
[2024-03-23T20:57:14.255+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 7
[2024-03-23T20:57:14.283+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_s3_connection> on 2024-03-21 05:17:00+00:00
[2024-03-23T20:57:14.293+0000] {standard_task_runner.py:60} INFO - Started process 11297 to run task
[2024-03-23T20:57:14.298+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3_data_extraction_v1', 'create_s3_connection', 'scheduled__2024-03-21T05:17:00+00:00', '--job-id', '1301', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpbiw1zaww']
[2024-03-23T20:57:14.302+0000] {standard_task_runner.py:88} INFO - Job 1301: Subtask create_s3_connection
[2024-03-23T20:57:14.377+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-21T05:17:00+00:00 [running]> on host ca1809388db1
[2024-03-23T20:57:14.495+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='spotify_to_s3_data_extraction_v1' AIRFLOW_CTX_TASK_ID='create_s3_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T05:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T05:17:00+00:00'
[2024-03-23T20:57:14.499+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_to_csvs_to_s3.py", line 143, in _create_connection
    raise AirflowFailException("Environment variables were not passed")
airflow.exceptions.AirflowFailException: Environment variables were not passed
[2024-03-23T20:57:14.515+0000] {taskinstance.py:1149} INFO - Immediate failure requested. Marking task as FAILED. dag_id=spotify_to_s3_data_extraction_v1, task_id=create_s3_connection, execution_date=20240321T051700, start_date=20240323T205714, end_date=20240323T205714
[2024-03-23T20:57:14.536+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1301 for task create_s3_connection (Environment variables were not passed; 11297)
[2024-03-23T20:57:14.554+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-23T20:57:14.596+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
