[2024-03-22T09:03:45.042+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-20T20:46:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
