[2024-03-21T07:36:21.708+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-21T05:13:00+00:00 [queued]>
[2024-03-21T07:36:21.728+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-21T05:13:00+00:00 [queued]>
[2024-03-21T07:36:21.729+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-03-21T07:36:21.765+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_s3_connection> on 2024-03-21 05:13:00+00:00
[2024-03-21T07:36:21.777+0000] {standard_task_runner.py:60} INFO - Started process 2324 to run task
[2024-03-21T07:36:21.789+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3_data_extraction_v1', 'create_s3_connection', 'scheduled__2024-03-21T05:13:00+00:00', '--job-id', '446', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpehj7gb10']
[2024-03-21T07:36:21.808+0000] {standard_task_runner.py:88} INFO - Job 446: Subtask create_s3_connection
[2024-03-21T07:36:21.945+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-21T05:13:00+00:00 [running]> on host ca1809388db1
[2024-03-21T07:36:22.160+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='spotify_to_s3_data_extraction_v1' AIRFLOW_CTX_TASK_ID='create_s3_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T05:13:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T05:13:00+00:00'
[2024-03-21T07:36:22.164+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_to_csvs_to_s3.py", line 143, in _create_connection
    raise AirflowFailException("Environment variables were not passed")
airflow.exceptions.AirflowFailException: Environment variables were not passed
[2024-03-21T07:36:22.186+0000] {taskinstance.py:1149} INFO - Immediate failure requested. Marking task as FAILED. dag_id=spotify_to_s3_data_extraction_v1, task_id=create_s3_connection, execution_date=20240321T051300, start_date=20240321T073621, end_date=20240321T073622
[2024-03-21T07:36:22.233+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 446 for task create_s3_connection (Environment variables were not passed; 2324)
[2024-03-21T07:36:22.291+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-21T07:36:22.502+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
