[2024-03-24T08:24:27.633+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_VV_Error-Resolve_x64.upload_csv_to_s3 manual__2024-03-24T08:13:45.471205+00:00 [queued]>
[2024-03-24T08:24:27.645+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_VV_Error-Resolve_x64.upload_csv_to_s3 manual__2024-03-24T08:13:45.471205+00:00 [queued]>
[2024-03-24T08:24:27.646+0000] {taskinstance.py:2193} INFO - Starting attempt 6 of 6
[2024-03-24T08:24:27.665+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): upload_csv_to_s3> on 2024-03-24 08:13:45.471205+00:00
[2024-03-24T08:24:27.674+0000] {standard_task_runner.py:60} INFO - Started process 2907 to run task
[2024-03-24T08:24:27.679+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3_data_extraction_VV_Error-Resolve_x64', 'upload_csv_to_s3', 'manual__2024-03-24T08:13:45.471205+00:00', '--job-id', '1397', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmph2yu720x']
[2024-03-24T08:24:27.683+0000] {standard_task_runner.py:88} INFO - Job 1397: Subtask upload_csv_to_s3
[2024-03-24T08:24:27.751+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_s3_data_extraction_VV_Error-Resolve_x64.upload_csv_to_s3 manual__2024-03-24T08:13:45.471205+00:00 [running]> on host bc244bd8b198
[2024-03-24T08:24:27.858+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='spotify_to_s3_data_extraction_VV_Error-Resolve_x64' AIRFLOW_CTX_TASK_ID='upload_csv_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-03-24T08:13:45.471205+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-24T08:13:45.471205+00:00'
[2024-03-24T08:24:27.860+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_to_csvs_to_s3.py", line 150, in upload_csv_to_s3
    print(csv_filenames + 'are the files to be uploaded')
TypeError: can only concatenate list (not "str") to list
[2024-03-24T08:24:27.873+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=spotify_to_s3_data_extraction_VV_Error-Resolve_x64, task_id=upload_csv_to_s3, execution_date=20240324T081345, start_date=20240324T082427, end_date=20240324T082427
[2024-03-24T08:24:27.889+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1397 for task upload_csv_to_s3 (can only concatenate list (not "str") to list; 2907)
[2024-03-24T08:24:27.933+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-24T08:24:27.958+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
