[2024-03-21T16:47:38.668+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-21T14:31:00+00:00 [queued]>
[2024-03-21T16:47:38.776+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-21T14:31:00+00:00 [queued]>
[2024-03-21T16:47:38.778+0000] {taskinstance.py:2193} INFO - Starting attempt 7 of 12
[2024-03-21T16:47:38.856+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): sptoify_to_csv> on 2024-03-21 14:31:00+00:00
[2024-03-21T16:47:38.904+0000] {standard_task_runner.py:60} INFO - Started process 3134 to run task
[2024-03-21T16:47:38.940+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3_data_extraction_v1', 'sptoify_to_csv', 'scheduled__2024-03-21T14:31:00+00:00', '--job-id', '622', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmpejdsnldn']
[2024-03-21T16:47:38.981+0000] {standard_task_runner.py:88} INFO - Job 622: Subtask sptoify_to_csv
[2024-03-21T16:47:39.442+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_s3_data_extraction_v1.sptoify_to_csv scheduled__2024-03-21T14:31:00+00:00 [running]> on host ca1809388db1
[2024-03-21T16:47:40.183+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='spotify_to_s3_data_extraction_v1' AIRFLOW_CTX_TASK_ID='sptoify_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-03-21T14:31:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-21T14:31:00+00:00'
[2024-03-21T16:47:40.187+0000] {logging_mixin.py:188} INFO - The extract function has been executed and this is data in the next line
[2024-03-21T16:47:40.189+0000] {logging_mixin.py:188} INFO - Initiating the Endpoint...
[2024-03-21T16:47:42.315+0000] {logging_mixin.py:188} INFO - Extracting other available tracks
[2024-03-21T16:47:58.367+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-03-21T16:47:58.382+0000] {process_utils.py:131} INFO - Sending 15 to group 3134. PIDs of all processes in the group: [3134]
[2024-03-21T16:47:58.384+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 3134
[2024-03-21T16:47:58.387+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-21T16:47:58.433+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_to_csvs_to_s3.py", line 64, in Spotify_to_CSV
    top_tracks = sp.next(top_tracks['tracks'])
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 347, in next
    return self._get(result["next"])
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 323, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/spotipy/client.py", line 266, in _internal_call
    response = self._session.request(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-21T16:47:58.544+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_to_s3_data_extraction_v1, task_id=sptoify_to_csv, execution_date=20240321T143100, start_date=20240321T164738, end_date=20240321T164758
[2024-03-21T16:47:58.599+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 622 for task sptoify_to_csv (Task received SIGTERM signal; 3134)
[2024-03-21T16:47:58.708+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3134, status='terminated', exitcode=1, started='16:47:38') (3134) terminated with exit code 1
