[2024-03-22T09:06:32.497+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-20T21:18:00+00:00 [queued]>
[2024-03-22T09:06:32.525+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-20T21:18:00+00:00 [queued]>
[2024-03-22T09:06:32.527+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 8
[2024-03-22T09:06:32.570+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): create_s3_connection> on 2024-03-20 21:18:00+00:00
[2024-03-22T09:06:32.584+0000] {standard_task_runner.py:60} INFO - Started process 4830 to run task
[2024-03-22T09:06:32.592+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_to_s3_data_extraction_v1', 'create_s3_connection', 'scheduled__2024-03-20T21:18:00+00:00', '--job-id', '957', '--raw', '--subdir', 'DAGS_FOLDER/spotify_to_csvs_to_s3.py', '--cfg-path', '/tmp/tmp5176koi6']
[2024-03-22T09:06:32.601+0000] {standard_task_runner.py:88} INFO - Job 957: Subtask create_s3_connection
[2024-03-22T09:06:32.723+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_to_s3_data_extraction_v1.create_s3_connection scheduled__2024-03-20T21:18:00+00:00 [running]> on host ca1809388db1
[2024-03-22T09:06:32.997+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Nathaniel Solomon' AIRFLOW_CTX_DAG_ID='spotify_to_s3_data_extraction_v1' AIRFLOW_CTX_TASK_ID='create_s3_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-03-20T21:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-20T21:18:00+00:00'
[2024-03-22T09:06:33.002+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/spotify_to_csvs_to_s3.py", line 143, in _create_connection
    raise AirflowFailException("Environment variables were not passed")
airflow.exceptions.AirflowFailException: Environment variables were not passed
[2024-03-22T09:06:33.025+0000] {taskinstance.py:1149} INFO - Immediate failure requested. Marking task as FAILED. dag_id=spotify_to_s3_data_extraction_v1, task_id=create_s3_connection, execution_date=20240320T211800, start_date=20240322T090632, end_date=20240322T090633
[2024-03-22T09:06:33.062+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 957 for task create_s3_connection (Environment variables were not passed; 4830)
[2024-03-22T09:06:33.097+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-22T09:06:33.156+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
